import { execFileSync } from "node:child_process";
import { existsSync, renameSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { describeLabelFilter, parseLabelFilter } from "./labels.ts";

// The full set of settings the daemon reads from the environment. The wizard
// collects these; the daemon reads them back via envOr() at startup.
export type YimbotConfig = {
  apiKey: string;
  teamName: string;
  deployStateName: string;
  reviewStateName: string;
  todoStateName: string;
  heartbeatIntervalMinutes: number;
  codebasePath: string;
  planModel: string;
  implModel: string;
  autoClaim: boolean;
  riskLabels: string[];
  maxInProgress: number;
  autoCleanup: boolean;
  autoContinue: boolean;
  maxContinuations: number;
  acJudgeModel: string;
  labelFilter: string;
  autoRefine: boolean;
  refineUsers: string;
  refineLabelFilter: string;
  maxRefining: number;
};

// Where the daemon's --env-file points (relative to the project root, which is
// pnpm's cwd for `pnpm start` / `pnpm onboard`).
export const envPath = join(process.cwd(), ".env");

// True once the one required setting is present. LINEAR_API_KEY is the only
// hard requirement; everything else has a default, so its absence is what marks
// a fresh, never-configured install that should be walked through setup.
export function isConfigured(env: NodeJS.ProcessEnv): boolean {
  return Boolean(env.LINEAR_API_KEY?.trim());
}

// Expand a leading ~ to the home directory. The daemon does no tilde expansion,
// so paths must be absolute in .env; the wizard expands before writing.
export function expandTilde(path: string): string {
  if (path === "~") return homedir();
  if (path.startsWith("~/")) return join(homedir(), path.slice(2));
  return path;
}

// Whether a path is an existing git repository — the CODEBASE_PATH invariant the
// daemon enforces at startup, checked here so the wizard catches it up front.
export function isGitRepo(path: string): boolean {
  const dir = expandTilde(path);
  if (!existsSync(dir)) return false;
  try {
    execFileSync("git", ["-C", dir, "rev-parse", "--git-dir"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

// The config as an ordered KEY→value map. Single source of truth for both the
// .env file text and the in-process env applied on an auto-run first launch.
export function configToEnvRecord(c: YimbotConfig): Record<string, string> {
  return {
    LINEAR_API_KEY: c.apiKey,
    LINEAR_TEAM_NAME: c.teamName,
    DEPLOY_STATE_NAME: c.deployStateName,
    REVIEW_STATE_NAME: c.reviewStateName,
    HEARTBEAT_INTERVAL_MINUTES: String(c.heartbeatIntervalMinutes),
    CODEBASE_PATH: c.codebasePath,
    PLAN_MODEL: c.planModel,
    IMPL_MODEL: c.implModel,
    AUTO_CLAIM: String(c.autoClaim),
    TODO_STATE_NAME: c.todoStateName,
    RISK_LABELS: c.riskLabels.join(","),
    MAX_IN_PROGRESS: String(c.maxInProgress),
    LABEL_FILTER: c.labelFilter,
    AUTO_CLEANUP: String(c.autoCleanup),
    AUTO_CONTINUE: String(c.autoContinue),
    MAX_CONTINUATIONS: String(c.maxContinuations),
    AC_JUDGE_MODEL: c.acJudgeModel,
    AUTO_REFINE: String(c.autoRefine),
    REFINE_USERS: c.refineUsers,
    REFINE_LABEL_FILTER: c.refineLabelFilter,
    MAX_REFINING: String(c.maxRefining),
  };
}

// The 21 keys this file's generated sections own. Anything else found in an
// existing .env is a hand-edited setting (BLOCKED_LABEL, TUI_*, ...) that a
// regenerated file must not drop.
const OWNED_ENV_KEYS = new Set([
  "LINEAR_API_KEY",
  "LINEAR_TEAM_NAME",
  "DEPLOY_STATE_NAME",
  "REVIEW_STATE_NAME",
  "HEARTBEAT_INTERVAL_MINUTES",
  "CODEBASE_PATH",
  "PLAN_MODEL",
  "IMPL_MODEL",
  "AUTO_CLAIM",
  "TODO_STATE_NAME",
  "RISK_LABELS",
  "MAX_IN_PROGRESS",
  "LABEL_FILTER",
  "AUTO_CLEANUP",
  "AUTO_CONTINUE",
  "MAX_CONTINUATIONS",
  "AC_JUDGE_MODEL",
  "AUTO_REFINE",
  "REFINE_USERS",
  "REFINE_LABEL_FILTER",
  "MAX_REFINING",
]);

// The KEY=value lines of an existing .env that this file's generated sections
// do not own, so a regenerated file can carry them forward instead of losing
// them. Comments and blank lines are not preserved; only settings matter.
export function extractPassthroughLines(existing: string): string[] {
  return existing.split("\n").filter((line) => {
    const key = line.trim().match(/^([A-Za-z_][A-Za-z0-9_]*)=/)?.[1];
    return key !== undefined && !OWNED_ENV_KEYS.has(key);
  });
}

// Render .env with section comments, grouped the same way as .env.example.
// passthroughLines carries forward settings the generated sections above
// don't own, so a save never drops a hand-edited value.
export function serializeEnvFile(c: YimbotConfig, passthroughLines: string[] = []): string {
  const r = configToEnvRecord(c);
  const lines = [
    "# yimbot configuration — generated by `pnpm onboard`. Re-run it to change these.",
    "",
    `LINEAR_API_KEY=${r.LINEAR_API_KEY}`,
    `LINEAR_TEAM_NAME=${r.LINEAR_TEAM_NAME}`,
    `DEPLOY_STATE_NAME=${r.DEPLOY_STATE_NAME}`,
    `REVIEW_STATE_NAME=${r.REVIEW_STATE_NAME}`,
    `HEARTBEAT_INTERVAL_MINUTES=${r.HEARTBEAT_INTERVAL_MINUTES}`,
    `CODEBASE_PATH=${r.CODEBASE_PATH}`,
    "",
    "# --- Session models (Claude Code model alias or id) ---",
    `PLAN_MODEL=${r.PLAN_MODEL}`,
    `IMPL_MODEL=${r.IMPL_MODEL}`,
    "",
    "# --- Autonomous claim step ---",
    `AUTO_CLAIM=${r.AUTO_CLAIM}`,
    `TODO_STATE_NAME=${r.TODO_STATE_NAME}`,
    `RISK_LABELS=${r.RISK_LABELS}`,
    `MAX_IN_PROGRESS=${r.MAX_IN_PROGRESS}`,
    `LABEL_FILTER=${r.LABEL_FILTER}`,
    "",
    "# --- Cleanup step ---",
    `AUTO_CLEANUP=${r.AUTO_CLEANUP}`,
    "",
    "# --- Advance step ---",
    `AUTO_CONTINUE=${r.AUTO_CONTINUE}`,
    `MAX_CONTINUATIONS=${r.MAX_CONTINUATIONS}`,
    `AC_JUDGE_MODEL=${r.AC_JUDGE_MODEL}`,
    "",
    "# --- Refine step ---",
    `AUTO_REFINE=${r.AUTO_REFINE}`,
    `REFINE_USERS=${r.REFINE_USERS}`,
    `REFINE_LABEL_FILTER=${r.REFINE_LABEL_FILTER}`,
    `MAX_REFINING=${r.MAX_REFINING}`,
  ];
  if (passthroughLines.length > 0) {
    lines.push("", "# --- Hand-edited settings this file's writer doesn't manage (preserved) ---", ...passthroughLines);
  }
  lines.push("");
  return lines.join("\n");
}

// Write .env, backing up any existing file to .env.bak first. Mode 0600 because
// it holds the Linear API key.
export function writeEnvFile(contents: string, path: string = envPath): void {
  if (existsSync(path)) renameSync(path, `${path}.bak`);
  writeFileSync(path, contents, { mode: 0o600 });
}

// The off-values a boolean setting recognizes. Shared so the wizard, the daemon
// and the settings panel cannot disagree about what "off" means.
export function isOff(value: string): boolean {
  return ["false", "off", "no", "0"].includes(value.trim().toLowerCase());
}

export function isPositiveInt(raw: string): boolean {
  const n = Number(raw);
  return Number.isInteger(n) && n >= 1;
}

export function isPositiveNumber(raw: string): boolean {
  const n = Number(raw);
  return Number.isFinite(n) && n > 0;
}

export function parseCommaList(raw: string): string[] {
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

// Read the config the daemon would run with, defaults and legacy names included.
// The inverse of configToEnvRecord, and the single source of truth for defaults:
// the wizard reads it for its initial values and the settings panel for its rows.
export function configFromEnv(env: NodeJS.ProcessEnv): YimbotConfig {
  const or = (name: string, fallback: string): string => {
    const v = env[name]?.trim();
    return v ? v : fallback;
  };
  return {
    apiKey: or("LINEAR_API_KEY", ""),
    teamName: or("LINEAR_TEAM_NAME", "Engineering"),
    deployStateName: or("DEPLOY_STATE_NAME", or("TRIGGER_STATE_NAME", "In Progress")),
    reviewStateName: or("REVIEW_STATE_NAME", "In Review"),
    todoStateName: or("TODO_STATE_NAME", "Todo"),
    heartbeatIntervalMinutes: Number(or("HEARTBEAT_INTERVAL_MINUTES", or("POLL_INTERVAL_MINUTES", "3"))),
    codebasePath: or("CODEBASE_PATH", join(homedir(), "Work/gemini")),
    planModel: or("PLAN_MODEL", "opus"),
    implModel: or("IMPL_MODEL", "sonnet"),
    autoClaim: !isOff(or("AUTO_CLAIM", or("AUTO_PICK", "true"))),
    riskLabels: parseCommaList(or("RISK_LABELS", "migration,infra,security,breaking")),
    maxInProgress: Number(or("MAX_IN_PROGRESS", "3")),
    autoCleanup: !isOff(or("AUTO_CLEANUP", "true")),
    autoContinue: !isOff(or("AUTO_CONTINUE", "true")),
    maxContinuations: Number(or("MAX_CONTINUATIONS", "5")),
    acJudgeModel: or("AC_JUDGE_MODEL", ""),
    labelFilter: or("LABEL_FILTER", ""),
    autoRefine: !isOff(or("AUTO_REFINE", "true")),
    refineUsers: or("REFINE_USERS", ""),
    refineLabelFilter: or("REFINE_LABEL_FILTER", ""),
    maxRefining: Number(or("MAX_REFINING", "1")),
  };
}

export type EditorKind =
  | "text"
  | "secret"
  | "number"
  | "toggle"
  | "list"
  | "pickTeam"
  | "pickState"
  | "labelFilter"
  | "readonly";

export type SettingRow = {
  envKey: string;
  label: string;
  editor: EditorKind;
  value: string;
  display: string;
};

function maskKey(key: string): string {
  if (!key) return "(not set)";
  if (key.length < 14) return "*".repeat(8);
  const head = key.slice(0, 4);
  return `${head}${"*".repeat(6)}${key.slice(-4)}`;
}

const ROW_SPECS: { envKey: string; label: string; editor: EditorKind }[] = [
  { envKey: "LINEAR_API_KEY", label: "linear api key", editor: "secret" },
  { envKey: "ASSIGNEE", label: "assignee", editor: "readonly" },
  { envKey: "LINEAR_TEAM_NAME", label: "team", editor: "pickTeam" },
  { envKey: "DEPLOY_STATE_NAME", label: "deploy state", editor: "pickState" },
  { envKey: "TODO_STATE_NAME", label: "todo state", editor: "pickState" },
  { envKey: "REVIEW_STATE_NAME", label: "review state", editor: "pickState" },
  { envKey: "LABEL_FILTER", label: "tickets", editor: "labelFilter" },
  { envKey: "MAX_IN_PROGRESS", label: "wip cap", editor: "number" },
  { envKey: "AUTO_CLAIM", label: "auto-claim", editor: "toggle" },
  { envKey: "AUTO_REFINE", label: "auto-refine", editor: "toggle" },
  { envKey: "REFINE_USERS", label: "refine users", editor: "text" },
  { envKey: "REFINE_LABEL_FILTER", label: "refine tickets", editor: "labelFilter" },
  { envKey: "MAX_REFINING", label: "refine cap", editor: "number" },
  { envKey: "RISK_LABELS", label: "risk labels", editor: "list" },
  { envKey: "HEARTBEAT_INTERVAL_MINUTES", label: "heartbeat minutes", editor: "number" },
  { envKey: "CODEBASE_PATH", label: "codebase path", editor: "text" },
  { envKey: "PLAN_MODEL", label: "plan model", editor: "text" },
  { envKey: "IMPL_MODEL", label: "impl model", editor: "text" },
  { envKey: "AUTO_CLEANUP", label: "auto-cleanup", editor: "toggle" },
  { envKey: "AUTO_CONTINUE", label: "auto-continue", editor: "toggle" },
  { envKey: "MAX_CONTINUATIONS", label: "max continuations", editor: "number" },
  { envKey: "AC_JUDGE_MODEL", label: "judge model", editor: "text" },
];

function displayValue(envKey: string, value: string): string {
  switch (envKey) {
    case "LINEAR_API_KEY":
      return maskKey(value);
    case "LABEL_FILTER":
      return describeLabelFilter(parseLabelFilter(value));
    case "RISK_LABELS":
      return parseCommaList(value).join(", ") || "(none)";
    case "AUTO_CLAIM":
    case "AUTO_CLEANUP":
    case "AUTO_CONTINUE":
    case "AUTO_REFINE":
      return isOff(value) ? "off" : "on";
    case "AC_JUDGE_MODEL":
      return value || "(claude default)";
    case "REFINE_USERS":
      return value || "(this API key)";
    case "REFINE_LABEL_FILTER":
      return value ? describeLabelFilter(parseLabelFilter(value)) : "(inherits tickets filter)";
    default:
      return value;
  }
}

function rowsFrom(record: Record<string, string>, assignee: string): SettingRow[] {
  return ROW_SPECS.map((spec) => {
    const value = spec.envKey === "ASSIGNEE" ? assignee : (record[spec.envKey] ?? "");
    const display =
      spec.envKey === "ASSIGNEE" ? `${assignee || "unknown"} (this API key)` : displayValue(spec.envKey, value);
    return { ...spec, value, display };
  });
}

export function settingRows(config: YimbotConfig, assignee: string): SettingRow[] {
  return rowsFrom(configToEnvRecord(config), assignee);
}

export type Draft = { base: YimbotConfig; edits: Record<string, string> };

export function newDraft(base: YimbotConfig): Draft {
  return { base, edits: {} };
}

export function setEdit(draft: Draft, envKey: string, raw: string): Draft {
  const edits = { ...draft.edits };
  if (raw === configToEnvRecord(draft.base)[envKey]) delete edits[envKey];
  else edits[envKey] = raw;
  return { base: draft.base, edits };
}

export function dirtyKeys(draft: Draft): string[] {
  return Object.keys(draft.edits);
}

export function draftRows(draft: Draft, assignee: string): SettingRow[] {
  return rowsFrom({ ...configToEnvRecord(draft.base), ...draft.edits }, assignee);
}

export function validateDraft(draft: Draft): Record<string, string> {
  const errors: Record<string, string> = {};
  for (const [envKey, raw] of Object.entries(draft.edits)) {
    switch (envKey) {
      case "MAX_IN_PROGRESS":
      case "MAX_CONTINUATIONS":
      case "MAX_REFINING":
        if (!isPositiveInt(raw)) errors[envKey] = "must be a positive integer";
        break;
      case "HEARTBEAT_INTERVAL_MINUTES":
        if (!isPositiveNumber(raw)) errors[envKey] = "must be a positive number";
        break;
      case "CODEBASE_PATH":
        if (!isGitRepo(raw)) errors[envKey] = "must be an existing git repository";
        break;
      // These non-empty rules match the wizard's Required validators.
      case "LINEAR_API_KEY":
      case "LINEAR_TEAM_NAME":
      case "DEPLOY_STATE_NAME":
      case "TODO_STATE_NAME":
      case "REVIEW_STATE_NAME":
      case "PLAN_MODEL":
      case "IMPL_MODEL":
        if (!raw.trim()) errors[envKey] = "cannot be empty";
        break;
    }
  }
  return errors;
}

export function commitDraft(draft: Draft): YimbotConfig {
  const errors = validateDraft(draft);
  const first = Object.entries(errors)[0];
  if (first) throw new Error(`${first[0]} ${first[1]}`);
  const edits = { ...draft.edits };
  // Validated tilde-expanded via isGitRepo, but the daemon does no expansion
  // itself, so a literal "~/..." must not reach .env.
  if ("CODEBASE_PATH" in edits) edits.CODEBASE_PATH = expandTilde(edits.CODEBASE_PATH);
  return configFromEnv({ ...configToEnvRecord(draft.base), ...edits });
}
