import { execFileSync } from "node:child_process";
import { existsSync, renameSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

// The full set of settings the daemon reads from the environment. The wizard
// collects these; the daemon reads them back via envOr() at startup.
export type YimbotConfig = {
  apiKey: string;
  teamName: string;
  deployStateName: string;
  reviewStateName: string;
  todoStateName: string;
  heartbeatIntervalMinutes: number;
  codebasePath: string;
  planModel: string;
  implModel: string;
  autoClaim: boolean;
  riskLabels: string[];
  maxInProgress: number;
  autoCleanup: boolean;
  autoContinue: boolean;
  maxContinuations: number;
  acJudgeModel: string;
  labelFilter: string;
};

// Where the daemon's --env-file points (relative to the project root, which is
// pnpm's cwd for `pnpm start` / `pnpm onboard`).
export const envPath = join(process.cwd(), ".env");

// True once the one required setting is present. LINEAR_API_KEY is the only
// hard requirement; everything else has a default, so its absence is what marks
// a fresh, never-configured install that should be walked through setup.
export function isConfigured(env: NodeJS.ProcessEnv): boolean {
  return Boolean(env.LINEAR_API_KEY?.trim());
}

// Expand a leading ~ to the home directory. The daemon does no tilde expansion,
// so paths must be absolute in .env; the wizard expands before writing.
export function expandTilde(path: string): string {
  if (path === "~") return homedir();
  if (path.startsWith("~/")) return join(homedir(), path.slice(2));
  return path;
}

// Whether a path is an existing git repository — the CODEBASE_PATH invariant the
// daemon enforces at startup, checked here so the wizard catches it up front.
export function isGitRepo(path: string): boolean {
  const dir = expandTilde(path);
  if (!existsSync(dir)) return false;
  try {
    execFileSync("git", ["-C", dir, "rev-parse", "--git-dir"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

// The config as an ordered KEY→value map. Single source of truth for both the
// .env file text and the in-process env applied on an auto-run first launch.
export function configToEnvRecord(c: YimbotConfig): Record<string, string> {
  return {
    LINEAR_API_KEY: c.apiKey,
    LINEAR_TEAM_NAME: c.teamName,
    DEPLOY_STATE_NAME: c.deployStateName,
    REVIEW_STATE_NAME: c.reviewStateName,
    HEARTBEAT_INTERVAL_MINUTES: String(c.heartbeatIntervalMinutes),
    CODEBASE_PATH: c.codebasePath,
    PLAN_MODEL: c.planModel,
    IMPL_MODEL: c.implModel,
    AUTO_CLAIM: String(c.autoClaim),
    TODO_STATE_NAME: c.todoStateName,
    RISK_LABELS: c.riskLabels.join(","),
    MAX_IN_PROGRESS: String(c.maxInProgress),
    LABEL_FILTER: c.labelFilter,
    AUTO_CLEANUP: String(c.autoCleanup),
    AUTO_CONTINUE: String(c.autoContinue),
    MAX_CONTINUATIONS: String(c.maxContinuations),
    AC_JUDGE_MODEL: c.acJudgeModel,
  };
}

// Render .env with section comments, grouped the same way as .env.example.
export function serializeEnvFile(c: YimbotConfig): string {
  const r = configToEnvRecord(c);
  return [
    "# yimbot configuration — generated by `pnpm onboard`. Re-run it to change these.",
    "",
    `LINEAR_API_KEY=${r.LINEAR_API_KEY}`,
    `LINEAR_TEAM_NAME=${r.LINEAR_TEAM_NAME}`,
    `DEPLOY_STATE_NAME=${r.DEPLOY_STATE_NAME}`,
    `REVIEW_STATE_NAME=${r.REVIEW_STATE_NAME}`,
    `HEARTBEAT_INTERVAL_MINUTES=${r.HEARTBEAT_INTERVAL_MINUTES}`,
    `CODEBASE_PATH=${r.CODEBASE_PATH}`,
    "",
    "# --- Session models (Claude Code model alias or id) ---",
    `PLAN_MODEL=${r.PLAN_MODEL}`,
    `IMPL_MODEL=${r.IMPL_MODEL}`,
    "",
    "# --- Autonomous claim step ---",
    `AUTO_CLAIM=${r.AUTO_CLAIM}`,
    `TODO_STATE_NAME=${r.TODO_STATE_NAME}`,
    `RISK_LABELS=${r.RISK_LABELS}`,
    `MAX_IN_PROGRESS=${r.MAX_IN_PROGRESS}`,
    `LABEL_FILTER=${r.LABEL_FILTER}`,
    "",
    "# --- Cleanup step ---",
    `AUTO_CLEANUP=${r.AUTO_CLEANUP}`,
    "",
    "# --- Advance step ---",
    `AUTO_CONTINUE=${r.AUTO_CONTINUE}`,
    `MAX_CONTINUATIONS=${r.MAX_CONTINUATIONS}`,
    `AC_JUDGE_MODEL=${r.AC_JUDGE_MODEL}`,
    "",
  ].join("\n");
}

// Write .env, backing up any existing file to .env.bak first. Mode 0600 because
// it holds the Linear API key.
export function writeEnvFile(contents: string, path: string = envPath): void {
  if (existsSync(path)) renameSync(path, `${path}.bak`);
  writeFileSync(path, contents, { mode: 0o600 });
}

// The off-values a boolean setting recognizes. Shared so the wizard, the daemon
// and the settings panel cannot disagree about what "off" means.
export function isOff(value: string): boolean {
  return ["false", "off", "no", "0"].includes(value.trim().toLowerCase());
}

export function isPositiveInt(raw: string): boolean {
  const n = Number(raw);
  return Number.isInteger(n) && n >= 1;
}

export function isPositiveNumber(raw: string): boolean {
  const n = Number(raw);
  return Number.isFinite(n) && n > 0;
}

export function parseCommaList(raw: string): string[] {
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

// Read the config the daemon would run with, defaults and legacy names included.
// The inverse of configToEnvRecord, and the single source of truth for defaults:
// the wizard reads it for its initial values and the settings panel for its rows.
export function configFromEnv(env: NodeJS.ProcessEnv): YimbotConfig {
  const or = (name: string, fallback: string): string => {
    const v = env[name]?.trim();
    return v ? v : fallback;
  };
  return {
    apiKey: or("LINEAR_API_KEY", ""),
    teamName: or("LINEAR_TEAM_NAME", "Engineering"),
    deployStateName: or("DEPLOY_STATE_NAME", or("TRIGGER_STATE_NAME", "In Progress")),
    reviewStateName: or("REVIEW_STATE_NAME", "In Review"),
    todoStateName: or("TODO_STATE_NAME", "Todo"),
    heartbeatIntervalMinutes: Number(or("HEARTBEAT_INTERVAL_MINUTES", or("POLL_INTERVAL_MINUTES", "3"))),
    codebasePath: or("CODEBASE_PATH", join(homedir(), "Work/gemini")),
    planModel: or("PLAN_MODEL", "opus"),
    implModel: or("IMPL_MODEL", "sonnet"),
    autoClaim: !isOff(or("AUTO_CLAIM", or("AUTO_PICK", "true"))),
    riskLabels: parseCommaList(or("RISK_LABELS", "migration,infra,security,breaking")),
    maxInProgress: Number(or("MAX_IN_PROGRESS", "3")),
    autoCleanup: !isOff(or("AUTO_CLEANUP", "true")),
    autoContinue: !isOff(or("AUTO_CONTINUE", "true")),
    maxContinuations: Number(or("MAX_CONTINUATIONS", "5")),
    acJudgeModel: or("AC_JUDGE_MODEL", ""),
    labelFilter: or("LABEL_FILTER", ""),
  };
}
