import { execFileSync } from "node:child_process";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readlinkSync,
  renameSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, isAbsolute, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as p from "@clack/prompts";
import { envOr } from "./env.ts";
import { fetchTeamStates, fetchTeams, fetchViewer } from "./linear-api.ts";
import { endSessionScriptPath, sessionScriptPath } from "./watcher.ts";

// The full set of settings the daemon reads from the environment. The wizard
// collects these; the daemon reads them back via envOr() at startup.
export type YimbotConfig = {
  apiKey: string;
  teamName: string;
  deployStateName: string;
  reviewStateName: string;
  todoStateName: string;
  heartbeatIntervalMinutes: number;
  codebasePath: string;
  planModel: string;
  implModel: string;
  autoClaim: boolean;
  riskLabels: string[];
  maxInProgress: number;
  autoCleanup: boolean;
};

// Where the daemon's --env-file points (relative to the project root, which is
// pnpm's cwd for `pnpm start` / `pnpm onboard`).
export const envPath = join(process.cwd(), ".env");

// True once the one required setting is present. LINEAR_API_KEY is the only
// hard requirement; everything else has a default, so its absence is what marks
// a fresh, never-configured install that should be walked through setup.
export function isConfigured(env: NodeJS.ProcessEnv): boolean {
  return Boolean(env.LINEAR_API_KEY?.trim());
}

// Expand a leading ~ to the home directory. The daemon does no tilde expansion,
// so paths must be absolute in .env; the wizard expands before writing.
export function expandTilde(path: string): string {
  if (path === "~") return homedir();
  if (path.startsWith("~/")) return join(homedir(), path.slice(2));
  return path;
}

// Whether a path is an existing git repository — the CODEBASE_PATH invariant the
// daemon enforces at startup, checked here so the wizard catches it up front.
export function isGitRepo(path: string): boolean {
  const dir = expandTilde(path);
  if (!existsSync(dir)) return false;
  try {
    execFileSync("git", ["-C", dir, "rev-parse", "--git-dir"], { stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

// The config as an ordered KEY→value map. Single source of truth for both the
// .env file text and the in-process env applied on an auto-run first launch.
export function configToEnvRecord(c: YimbotConfig): Record<string, string> {
  return {
    LINEAR_API_KEY: c.apiKey,
    LINEAR_TEAM_NAME: c.teamName,
    DEPLOY_STATE_NAME: c.deployStateName,
    REVIEW_STATE_NAME: c.reviewStateName,
    HEARTBEAT_INTERVAL_MINUTES: String(c.heartbeatIntervalMinutes),
    CODEBASE_PATH: c.codebasePath,
    PLAN_MODEL: c.planModel,
    IMPL_MODEL: c.implModel,
    AUTO_CLAIM: String(c.autoClaim),
    TODO_STATE_NAME: c.todoStateName,
    RISK_LABELS: c.riskLabels.join(","),
    MAX_IN_PROGRESS: String(c.maxInProgress),
    AUTO_CLEANUP: String(c.autoCleanup),
  };
}

// Render .env with section comments, grouped the same way as .env.example.
export function serializeEnvFile(c: YimbotConfig): string {
  const r = configToEnvRecord(c);
  return [
    "# yimbot configuration — generated by `pnpm onboard`. Re-run it to change these.",
    "",
    `LINEAR_API_KEY=${r.LINEAR_API_KEY}`,
    `LINEAR_TEAM_NAME=${r.LINEAR_TEAM_NAME}`,
    `DEPLOY_STATE_NAME=${r.DEPLOY_STATE_NAME}`,
    `REVIEW_STATE_NAME=${r.REVIEW_STATE_NAME}`,
    `HEARTBEAT_INTERVAL_MINUTES=${r.HEARTBEAT_INTERVAL_MINUTES}`,
    `CODEBASE_PATH=${r.CODEBASE_PATH}`,
    "",
    "# --- Session models (Claude Code model alias or id) ---",
    `PLAN_MODEL=${r.PLAN_MODEL}`,
    `IMPL_MODEL=${r.IMPL_MODEL}`,
    "",
    "# --- Autonomous claim step ---",
    `AUTO_CLAIM=${r.AUTO_CLAIM}`,
    `TODO_STATE_NAME=${r.TODO_STATE_NAME}`,
    `RISK_LABELS=${r.RISK_LABELS}`,
    `MAX_IN_PROGRESS=${r.MAX_IN_PROGRESS}`,
    "",
    "# --- Cleanup step ---",
    `AUTO_CLEANUP=${r.AUTO_CLEANUP}`,
    "",
  ].join("\n");
}

// Write .env, backing up any existing file to .env.bak first. Mode 0600 because
// it holds the Linear API key.
export function writeEnvFile(contents: string, path: string = envPath): void {
  if (existsSync(path)) renameSync(path, `${path}.bak`);
  writeFileSync(path, contents, { mode: 0o600 });
}

const errMsg = (e: unknown): string => (e instanceof Error ? e.message : String(e));

// Abort cleanly on Ctrl-C / Esc at any prompt. Nothing is written until the very
// end, so cancelling always leaves the existing config untouched.
function bail<T>(value: T | symbol): T {
  if (p.isCancel(value)) {
    p.cancel("Setup cancelled — no changes written.");
    process.exit(0);
  }
  return value;
}

// Repo root, so the wizard can link the vendored launcher + skill into place.
const repoRoot = fileURLToPath(new URL("..", import.meta.url));

type HostLink = { source: string; target: string; label: string };
const hostLinks: HostLink[] = [
  {
    source: join(repoRoot, "scripts/new-session.sh"),
    target: join(homedir(), "new-session.sh"),
    label: "session launcher (~/new-session.sh)",
  },
  {
    source: join(repoRoot, "scripts/end-session.sh"),
    target: join(homedir(), "end-session.sh"),
    label: "session teardown (~/end-session.sh)",
  },
  {
    source: join(repoRoot, "skills/pickup-ticket"),
    target: join(homedir(), ".claude/skills/pickup-ticket"),
    label: "pickup-ticket skill (~/.claude/skills/pickup-ticket)",
  },
  {
    source: join(repoRoot, "skills/address-pr-comments"),
    target: join(homedir(), ".claude/skills/address-pr-comments"),
    label: "address-pr-comments skill (~/.claude/skills/address-pr-comments)",
  },
];

// Whether `target` is already our symlink to `source`, some other existing
// file/dir, or absent. Drives whether the installer links, skips, or asks.
export function linkState(source: string, target: string): "ours" | "other" | "missing" {
  let stat;
  try {
    stat = lstatSync(target);
  } catch {
    return "missing";
  }
  if (stat.isSymbolicLink()) {
    try {
      if (readlinkSync(target).replace(/\/+$/, "") === source.replace(/\/+$/, "")) return "ours";
    } catch {
      /* unreadable link → treat as other */
    }
  }
  return "other";
}

// Symlink the repo's vendored launcher + skill into the places the daemon and
// Claude Code expect. Idempotent; never clobbers an unrelated existing file
// without asking (backs it up to .bak if the user agrees).
async function installHostLinks(): Promise<void> {
  const link = bail(
    await p.confirm({
      message: "Link yimbot's session launcher and pickup-ticket skill into place?",
      initialValue: true,
    }),
  );
  if (!link) return;
  const results: string[] = [];
  for (const { source, target, label } of hostLinks) {
    try {
      const state = linkState(source, target);
      if (state === "ours") {
        results.push(`[ok] ${label} already linked`);
        continue;
      }
      if (state === "other") {
        const replace = bail(
          await p.confirm({
            message: `${target} exists and isn't a yimbot link. Back it up (.bak) and replace with a link to the repo copy?`,
            initialValue: false,
          }),
        );
        if (!replace) {
          results.push(`[skip] ${label} left as-is`);
          continue;
        }
        renameSync(target, `${target}.bak`);
      }
      mkdirSync(dirname(target), { recursive: true });
      symlinkSync(source, target);
      results.push(`[ok] ${label} linked`);
    } catch (err) {
      results.push(`[fail] ${label}: ${errMsg(err)}`);
    }
  }
  p.note(results.join("\n"), "Install");
}

// Obtain an API key that authenticates. Offers to keep an existing key on a
// re-run; otherwise (or on any auth failure) prompts until one works.
async function resolveApiKey(): Promise<{ apiKey: string; viewerName: string }> {
  const existing = process.env.LINEAR_API_KEY?.trim();
  let candidate = "";
  if (existing) {
    const keep = bail(await p.confirm({ message: "Keep the existing Linear API key?", initialValue: true }));
    if (keep) candidate = existing;
  }
  while (true) {
    if (!candidate) {
      candidate = bail(
        await p.password({
          message: "Linear API key (Settings → Account → Security & Access)",
          validate: (v) => (v?.trim() ? undefined : "Required"),
        }),
      ).trim();
    }
    const s = p.spinner();
    s.start("Authenticating with Linear");
    try {
      const viewer = await fetchViewer(candidate);
      s.stop(`Authenticated as ${viewer.name}`);
      return { apiKey: candidate, viewerName: viewer.name };
    } catch (err) {
      s.stop(`Authentication failed: ${errMsg(err)}`);
      candidate = ""; // re-prompt
    }
  }
}

// Interactive first-run / reconfigure wizard. Validates against Linear as it
// goes, writes .env, and returns the collected config so an auto-run caller can
// start the daemon in the same process.
export async function runSetup(): Promise<YimbotConfig> {
  p.intro("yimbot setup");
  if (isConfigured(process.env)) {
    p.note("Existing .env found — current values are the defaults below; it will be backed up to .env.bak.");
  }

  const { apiKey, viewerName } = await resolveApiKey();

  const teamsSpin = p.spinner();
  teamsSpin.start("Loading teams");
  const teams = await fetchTeams(apiKey);
  teamsSpin.stop(`Loaded ${teams.length} team(s)`);
  if (teams.length === 0) {
    p.cancel("This account has no accessible teams.");
    process.exit(1);
  }
  const defaultTeam = envOr("LINEAR_TEAM_NAME", "Engineering");
  const teamId = bail(
    await p.select({
      message: "Team to watch",
      options: teams.map((t) => ({ value: t.id, label: t.name, hint: t.key })),
      initialValue:
        teams.find((t) => t.name.toLowerCase() === defaultTeam.toLowerCase())?.id ?? teams[0].id,
    }),
  );
  const teamName = teams.find((t) => t.id === teamId)!.name;

  const statesSpin = p.spinner();
  statesSpin.start("Loading workflow states");
  const states = await fetchTeamStates(apiKey, teamId);
  statesSpin.stop(`Loaded ${states.length} state(s)`);

  const pickState = async (message: string, defaultName: string): Promise<string> =>
    bail(
      await p.select({
        message,
        options: states.map((s) => ({ value: s.name, label: s.name, hint: s.type })),
        initialValue:
          states.find((s) => s.name.toLowerCase() === defaultName.toLowerCase())?.name ??
          states[0].name,
      }),
    );

  const deployStateName = await pickState(
    "Launch a session when an issue enters…",
    envOr("DEPLOY_STATE_NAME", envOr("TRIGGER_STATE_NAME", "In Progress")),
  );
  const reviewStateName = await pickState(
    'Your "In Review" state (flags a session ready to test)',
    envOr("REVIEW_STATE_NAME", "In Review"),
  );
  const todoStateName = await pickState(
    "Auto-claim ready work from…",
    envOr("TODO_STATE_NAME", "Todo"),
  );

  const codebasePath = expandTilde(
    bail(
      await p.text({
        message: "Codebase path (git repo pulled every poll)",
        initialValue: envOr("CODEBASE_PATH", join(homedir(), "Work/gemini")),
        validate: (v) => {
          const t = (v ?? "").trim();
          if (!t) return "Required";
          if (!isAbsolute(expandTilde(t))) return "Must be an absolute path";
          if (!isGitRepo(t)) return "Not an existing git repository";
          return undefined;
        },
      }),
    ).trim(),
  );

  const isPositive = (v: string | undefined) => Number(v) > 0 && Number.isFinite(Number(v));
  const heartbeatIntervalMinutes = Number(
    bail(
      await p.text({
        message: "Heartbeat interval (minutes) — how often to check the board",
        initialValue: envOr("HEARTBEAT_INTERVAL_MINUTES", envOr("POLL_INTERVAL_MINUTES", "3")),
        validate: (v) => (isPositive(v) ? undefined : "Must be a positive number"),
      }),
    ),
  );

  const planModel = bail(
    await p.text({
      message: "Model for planning (Claude Code alias or id, e.g. opus)",
      initialValue: envOr("PLAN_MODEL", "opus"),
      validate: (v) => (v?.trim() ? undefined : "Required"),
    }),
  ).trim();
  const implModel = bail(
    await p.text({
      message: "Model for implementing (runs the implementation subagents)",
      initialValue: envOr("IMPL_MODEL", "sonnet"),
      validate: (v) => (v?.trim() ? undefined : "Required"),
    }),
  ).trim();

  const autoClaimDefault = !["false", "off", "no", "0"].includes(
    envOr("AUTO_CLAIM", envOr("AUTO_PICK", "true")).toLowerCase(),
  );
  const autoClaim = bail(
    await p.confirm({ message: "Enable the autonomous claim step?", initialValue: autoClaimDefault }),
  );
  let riskLabels = envOr("RISK_LABELS", "migration,infra,security,breaking")
    .split(",")
    .map((l) => l.trim())
    .filter(Boolean);
  let maxInProgress = Number(envOr("MAX_IN_PROGRESS", "3"));
  if (autoClaim) {
    const labelsStr = bail(
      await p.text({
        message: "Never auto-claim tickets with these labels (comma-separated)",
        initialValue: riskLabels.join(","),
      }),
    );
    riskLabels = labelsStr
      .split(",")
      .map((l) => l.trim())
      .filter(Boolean);
    const maxStr = bail(
      await p.text({
        message: "Max tickets In Progress at once (WIP cap)",
        initialValue: String(Number.isInteger(maxInProgress) && maxInProgress >= 1 ? maxInProgress : 3),
        validate: (v) =>
          Number.isInteger(Number(v)) && Number(v) >= 1 ? undefined : "Enter a positive integer",
      }),
    );
    maxInProgress = Number(maxStr);
  }

  const autoCleanupDefault = !["false", "off", "no", "0"].includes(
    envOr("AUTO_CLEANUP", "true").toLowerCase(),
  );
  const autoCleanup = bail(
    await p.confirm({
      message: "Enable the cleanup step? (remove a worktree + session once its PR merges)",
      initialValue: autoCleanupDefault,
    }),
  );

  await installHostLinks();

  const preflight = [
    { path: sessionScriptPath, label: "~/new-session.sh", role: "launches worktree+tmux sessions (required)" },
    {
      path: endSessionScriptPath,
      label: "~/end-session.sh",
      role: "cleanup step: tears down merged PRs' worktrees (required for cleanup)",
    },
    {
      path: join(homedir(), ".claude/skills/pickup-ticket"),
      label: "~/.claude/skills/pickup-ticket",
      role: "plan→implement→review flow (required)",
    },
    {
      path: join(homedir(), ".claude/skills/address-pr-comments"),
      label: "~/.claude/skills/address-pr-comments",
      role: "review step: address PR comments (required for PR handling)",
    },
  ];
  p.note(
    preflight.map((c) => `${existsSync(c.path) ? "[ok]" : "[missing]"} ${c.label} — ${c.role}`).join("\n"),
    "Pre-flight",
  );
  if (!existsSync(sessionScriptPath)) {
    const proceed = bail(
      await p.confirm({
        message: "~/new-session.sh is missing; the daemon can't launch sessions without it. Save config anyway?",
        initialValue: true,
      }),
    );
    if (!proceed) {
      p.cancel("Setup cancelled — no changes written.");
      process.exit(0);
    }
  }

  const config: YimbotConfig = {
    apiKey,
    teamName,
    deployStateName,
    reviewStateName,
    todoStateName,
    heartbeatIntervalMinutes,
    codebasePath,
    planModel,
    implModel,
    autoClaim,
    riskLabels,
    maxInProgress,
    autoCleanup,
  };
  writeEnvFile(serializeEnvFile(config));
  p.outro(`Saved to .env — signed in as ${viewerName}, watching "${teamName}".`);
  return config;
}
